// <auto-generated />
namespace DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_introduce_tbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_introduce_tbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202208190415288_add_introduce_tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
